apiVersion: v1
kind: Service
metadata:
  name: devops-capstone-project-service
  labels:
    app: devops-capstone-project
spec:
  type: LoadBalancer # Or NodePort, depending on the K8s environment and user preference
  selector:
    app: devops-capstone-project # This must match the labels in your Deployment's template
  ports:
  - protocol: TCP
    port: 80       # Port exposed externally by the service
    targetPort: 8000 # Port on the container that the service will forward traffic to

